name: Test

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.5

      - name: Setup node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16.5.0'

      - name: Install dependencies
        run: npm ci

      - name: Lint check with ESLint
        run: npm run eslint

      - name: 'Send failure message to #developer-chat'
        if: failure() && github.ref == 'refs/heads/master'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: developer-chat
          status: FAILED
          color: danger

  # unit-tests:
  #   name: Unit tests
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2.3.5
  #       with:
  #         fetch-depth: 0
  #     - name: Setup node
  #       uses: actions/setup-node@v2.4.1
  #       with:
  #         node-version: '16.5.0'
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run tests
  #       run: |
  #         npm run test
  #     - name: 'Send failure message to #developer-chat'
  #       if: failure() && github.ref == 'refs/heads/master'
  #       env:
  #         SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
  #       uses: voxmedia/github-action-slack-notify-build@v1
  #       with:
  #         channel: developer-chat
  #         status: FAILED
  #         color: danger

  trigger-build:
    name: Trigger publish version
    runs-on: ubuntu-20.04

    needs: [lint]
    steps:
      - name: Publish new patch version
        if: github.ref == 'refs/heads/master'
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: Publish version
          token: ${{ secrets.BOT_TOKEN }}
          inputs: '{ "release-type": "patch" }'
      - name: Publish pre-release version
        if: github.ref != 'refs/heads/master'
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: Publish version
          token: ${{ secrets.BOT_TOKEN }}
          inputs: '{ "release-type": "prerelease" }'
          ref: ${{ github.event.pull_request.head.ref }}
